_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: fr
uuid: 9f32a305-0d69-40d4-9223-6f088076b8e2
name: 'Good Recipes'
mail: maninchristophe@yahoo.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: fr
